# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('person_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.StockDetails')),
            ],
        ),
    ]
