# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='person_data',
            new_name='stockdetails_data',
        ),
    ]
